### ISSUE TITLE
Double linking in GFM (encountered in 0.2.0.pre-4)

### ISSUE THREAD

**Issue by kkononov** [valich/intellij-markdown#28]
Example of input handled incorrectly:
```
[http://localhost:8000](http://localhost:8000)
```

Result (classnames are added on our side):

![image](https://user-images.githubusercontent.com/2767784/43588324-ea9d0e60-9674-11e8-9e09-e7b139004905.png)

**Comment by kkononov** [comment]
`baseURI` is set to `http://localhost:8000`

**Comment by valich** [comment]
Oh, this quite an interesting problem.

Formally, CommonMark spec [prohibits](https://spec.commonmark.org/0.28/#example-489) placing links inside of link texts. However, it looks like they've missed this thing for autolinks, too, at least looking at their [reference impl](https://spec.commonmark.org/dingus/?text=%5B*foo*%20and%20%3Chttps%3A%2F%2Fgoogle.com%3E%5D(%2Furi)%0A).

That's what happens in our case; since we use GFM autolinks, it's even worse.

Right now I am not sure how to fix that in the current architecture, but I just need more thinking time :)

**Comment by valich** [comment]
Fixed in 0.2.0.pre-5-kotlin-1.2.60
